name = "belles-terres-worker"
main = "src/index.js"
compatibility_date = "2025-11-11"

[[r2_buckets]]
binding = "LOGS_BUCKET"     # utilis√© dans le code (env.LOGS_BUCKET)
bucket_name = "bt-logs"     # nom de ton bucket R2
